### ISSUE TITLE
Missing include?

### ISSUE THREAD

**Issue by Alexdc-12** [jaylinski/xmltv#15]
I Installed via composer and added the test example to xml1.php and tried to run it, got the following error though

 Fatal error: Uncaught Error: Class 'XmlTv\Tv\Elements\DisplayName' not found in /var/www/api/xml1.php on line 11

Any ideas?

**Comment by jaylinski** [comment]
The readme references the (unreleased) version 2, which changed include namespaces.

Please refer to the example in https://github.com/jaylinski/xmltv/tree/v1.1.0.

Sorry about the confusion. Note to myself: release stable v2. :sweat_smile:

**Comment by jaylinski** [comment]
I released the stable v2 version.

https://github.com/jaylinski/xmltv/releases/tag/v2.0.0
