### ISSUE TITLE
small fix would be nice

### ISSUE THREAD

**Issue by tiger-seo** [jaylinski/xmltv#27]
https://github.com/jaylinski/xmltv/blob/b90c0dac590a9565bd458d814eed3e9a5b4e8e6b/src/Tv/Programme.php#L211

would be nice to remove this redundant phpdoc parameter spec; thanks.

**Comment by jaylinski** [comment]
@tiger-seo Thanks for the heads up. I now integrated PHPStan so I won't miss such things anymore.
